import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { logger } from "@/lib/logger";
import { getBaseUrl } from "@/lib/url";

/**
 * GET /api/auth/sso-login?token=xxx
 * Exchanges a one-time SSO token for a session via redirect to the
 * credentials login endpoint with a special SSO password.
 *
 * The token was generated by SAML/OIDC callback and stored in system_settings.
 * It expires after 5 minutes and is deleted after use.
 */
export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const token = url.searchParams.get("token");

    if (!token) {
      return NextResponse.redirect(
        new URL("/login?error=missing_token", req.url),
      );
    }

    // Look up the SSO token
    const tokenKey = `sso.token.${token}`;
    const tokenRecord = await prisma.system_settings.findUnique({
      where: { settingKey: tokenKey },
    });

    if (!tokenRecord || !tokenRecord.settingValue) {
      return NextResponse.redirect(
        new URL("/login?error=invalid_token", req.url),
      );
    }

    const data = JSON.parse(tokenRecord.settingValue);

    // Delete token immediately (one-time use)
    await prisma.system_settings.delete({ where: { settingKey: tokenKey } });

    // Check expiry
    if (new Date(data.expiresAt) < new Date()) {
      return NextResponse.redirect(
        new URL("/login?error=token_expired", req.url),
      );
    }

    // Find the user
    const user = await prisma.user.findUnique({
      where: { userid: data.userId },
      select: { userid: true, username: true },
    });

    if (!user || !user.username) {
      return NextResponse.redirect(
        new URL("/login?error=user_not_found", req.url),
      );
    }

    // Redirect to login page with SSO parameters that the login form can auto-submit
    const loginUrl = new URL("/login", getBaseUrl());
    loginUrl.searchParams.set("sso_user", user.username);
    loginUrl.searchParams.set("sso_token", token);

    return NextResponse.redirect(loginUrl);
  } catch (error: any) {
    logger.error("SSO login error", { error: error.message });
    return NextResponse.redirect(new URL("/login?error=sso_failed", req.url));
  }
}

export const dynamic = "force-dynamic";
